<a href="https://colab.research.google.com/github/CZY0428/-/blob/master/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


**1. Pytorch Documentation Explanation with torch.max**



In [3]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 0.9528, -2.1348, -0.2203, -1.0267,  0.4661],
        [ 0.4594, -1.3907,  0.4396,  0.4269, -1.9288],
        [ 1.6055, -0.6704, -0.4467, -2.2851, -0.1706],
        [ 1.5561, -1.3098,  0.7186, -0.1851,  0.7265]])
tensor([[-0.2526, -1.5579, -0.2162,  0.1137, -0.2608],
        [ 0.9790, -1.0832, -1.6169,  1.1630,  0.2462],
        [-1.7533, -1.5666, -0.9357,  1.0433, -1.1288],
        [ 0.5594, -0.6299,  0.9250, -1.1464, -0.8410]])
tensor([[-0.9480,  1.0263, -0.3100,  0.5243,  1.0143],
        [-1.1737,  1.0579,  1.0280,  0.2668,  1.1450],
        [ 1.1165,  0.9292,  1.0399,  1.7059,  0.6235],
        [-1.8382, -0.7156,  0.5921,  1.2322, -1.7340]])


In [4]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.6055)


In [2]:
import torch

In [7]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m ,idx = torch.max(x,0);
print(m)
print(idx)

tensor([ 1.6055, -0.6704,  0.7186,  0.4269,  0.7265])
tensor([2, 2, 3, 1, 3])


In [9]:
# 2-2
m,idx = torch.max(input=x, dim=0)
print(m)
print(idx)

# m, idx = torch.max(input=x,dim=0)
# print(m)
# print(idx)

tensor([ 1.6055, -0.6704,  0.7186,  0.4269,  0.7265])
tensor([2, 2, 3, 1, 3])


In [10]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([ 1.6055, -0.6704,  0.7186,  0.4269,  0.7265])
tensor([2, 2, 3, 1, 3])


In [13]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
max_val, _ = torch.max(x, dim=0, keepdim=True)
x_normalized = x - max_val
print(x_normalized)
print(m)
print(idx)

tensor([[-0.6527, -1.4644, -0.9389, -1.4535, -0.2603],
        [-1.1461, -0.7203, -0.2790,  0.0000, -2.6552],
        [ 0.0000,  0.0000, -1.1653, -2.7119, -0.8971],
        [-0.0493, -0.6394,  0.0000, -0.6119,  0.0000]])
tensor([[ 1.6055, -0.6704,  0.7186,  0.4269,  0.7265]])
tensor([[2, 2, 3, 1, 3]])


In [16]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([ 1.6055, -0.6704,  0.7186,  0.4269,  0.7265])
tensor([2, 2, 3, 1, 3])


In [1]:
# 2-6

p = (m,idx)
torch.max(x,0,False,out= p)
print(p[0])
print(p[1])

NameError: name 'm' is not defined

In [4]:
# 2-7
import torch
m, idx = torch.max(x,True)

NameError: name 'x' is not defined

In [2]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

NameError: name 'torch' is not defined

The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [2]:
import torch

In [5]:
# 1. different device error

model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(x)
print(y)

tensor([1., 2., 3., 4., 5.], device='cuda:0')
tensor([-1.0816], device='cuda:0', grad_fn=<ViewBackward0>)


In [6]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [10]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(4,5)
z = x + y

In [11]:
# 2. mismatched dimensions error (fixed)

z = x + y
print(z.shape)

torch.Size([4, 5])


In [4]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(1,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


torch.Size([1, 1000])


In [3]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = (d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 3, 244, 244])


In [7]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
print('before', labels)
labels = labels.long()
print('after', labels)
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

before tensor([1., 2., 3., 4., 0.])
after tensor([1, 2, 3, 4, 0])


In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [8]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [9]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

在使用数据加载器时，我们通常喜欢打乱数据（shuffle）。这就是 torch.utils.data.DataLoader 派上用场的地方。如果从 torch.utils.data.DataLoader 的角度来看，每条数据都是一个索引（0, 1, 2...），那么打乱数据就可以简单地通过打乱一个索引数组来完成。torch.utils.data.DataLoader 需要两个信息来完成其职责。首先，它需要知道数据的长度。其次，一旦 torch.utils.data.DataLoader 输出打乱后的索引，数据集就需要返回相应的（对应这个索引的）数据。

因此，torch.utils.data.Dataset 通过两个函数，__len__() 和 __getitem__() 来提供这些信息，从而支持 torch.utils.data.DataLoader 的工作。

In [10]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['b']
['t']
['p']
['g']
['a']
['j']
['e']
['d']
['n']
['r']
['q']
['v']
['s']
['w']
['z']
['u']
['h']
['m']
['c']
['i']
['l']
['x']
['y']
['f']
['o']
['k']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)